name = "aa228_final_project"
uuid = "a99c436d-89a3-49f9-91f5-532bd9003a66"
authors = ["Bradley Collicott <bcollico@stanford.edu>", "Daniel Neamati <dneamati@stanford.edu>", "Alexandros Tzikas <alextzik@stanford.edu>"]
version = "0.1.0"

[deps]
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
